# setting port values for external communication
# apiVersion: apps/v1
# kind: Service
# metadata:
#   labels:
#     name: nginx
#   name: nginx
# spec:
#   template:
#     metadata:
#       labels:
#         app: nginx
#   ports:
#   - name: "80"
#     port: 8888
#     targetPort: 80
#   selector:
#     name: nginx
#   type: NodePort

apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081


