apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeypot-deployment
spec:
  selector:
    matchLabels:
      app: honeypot
  replicas: 2
  template:
    metadata:
      labels:
        app: honeypot
    spec:
      containers:
        - name: honeypot
          image: honeypot:0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"